### ISSUE TITLE
Gradient stop with decimal

### ISSUE THREAD

**Issue by huan086** [ben-eb/postcss-minify-gradients#2]
`function isLessThan (a, b) {
    return a.unit === b.unit && parseInt(a.number, 10) >= parseInt(b.number, 10);
}`

assumes integer stop length. 

`linear-gradient(#fff, #fff 2em, #ccc 2em, #ccc 2.1em, #fff 2.1em)` breaks

**Comment by ben-eb** [comment]
Thanks for the report, resolved in `1.0.2`. 👍
